#include <cup.h>

int
main ()				//basic printing
{
  3print ("Hello World!");
  int a, b;
  a = 9;
  char z = 's';
  scan ("%d", &b);
  print ("%d", a);
  print ("%d", b);
  print ("%d", a + b);
  print ("%c", z);

  string str = "abcDEfghi";	//string functionss
  print ("%s", str);
  string str1 = substr (str, 1, 5);
  string str2 = lowercase (str);
  bool num = isNumeric (str);
  if (num)
    return 0;
}
